name = "queue-it-netacea-worker"
main = "./dist/worker.js"

account_id = "0ba360f2b62f26d1f1643d2ad07a65d4"
route = "queue.netacea-int.co.uk/*"

compatibility_date = "2023-07-24"

kv_namespaces = [
  { binding = "IntegrationConfigKV", id = "10a24f7cda464d39b926692c00d77b24", preview_id = "dcd97ae07436459d84655782bdb4cf8c" }
]